-- Post-init comments và documentation
-- File này được chạy tự động sau khi init_postgres.sql hoàn tất

-- Add table comments for documentation
COMMENT ON TABLE fraud_predictions IS 
'Stores fraud predictions for REAL-TIME transactions only.
- Real-time flow: Kafka CDC → Bronze streaming → transactions table → FastAPI prediction → fraud_predictions
- Chatbot/manual predictions (CHAT_*, MANUAL_*) are NOT saved here (API skips them)
- Foreign key ensures data integrity: only predictions for existing transactions are stored';

COMMENT ON COLUMN fraud_predictions.trans_num IS 'Transaction number - unique identifier for the transaction';
COMMENT ON COLUMN fraud_predictions.prediction_score IS 'ML model fraud probability score (0-1)';
COMMENT ON COLUMN fraud_predictions.is_fraud_predicted IS 'Binary fraud prediction: 0=legitimate, 1=fraud';
COMMENT ON COLUMN fraud_predictions.model_version IS 'Version of ML model used for prediction';

COMMENT ON TABLE chat_history IS 'Chat history for fraud detection chatbot - stores user queries and assistant responses';
COMMENT ON COLUMN chat_history.sql_query IS 'SQL query generated by LLM (if applicable)';

COMMENT ON TABLE transactions IS 'Sparkov transaction dataset - contains credit card transaction details and fraud labels';
COMMENT ON COLUMN transactions.trans_num IS 'Unique transaction identifier (primary key)';
COMMENT ON COLUMN transactions.is_fraud IS 'Ground truth fraud label: 0=legitimate, 1=fraud';

-- Verify all comments were added
SELECT 
    tablename,
    obj_description(('public.' || tablename)::regclass) as table_comment
FROM pg_tables 
WHERE schemaname = 'public' AND tablename IN ('fraud_predictions', 'chat_history', 'transactions')
ORDER BY tablename;
